### PR TITLE
Commit after first Branch

### PR DESCRIPTION
**Pull request by rdhayaalan**
New Pull Request

### CODE REVIEW

**Review by ZahraB21 — DISMISSED** [review]
@rdhayaalan Can you please change the name of the file to your name. So it would look like name.txt and do a pull request again. 
Thanks.

**Comment by rdhayaalan** [comment]
> @rdhayaalan Can you please change the name of the file to your name. So it would look like name.txt and do a pull request again.
> Thanks.

I Changed the file to Alan.txt

**Review by ZahraB21 — CHANGES_REQUESTED** [review]
Great job @rdhayaalan . 
However, we don't want the Test.txt file. Can you delete that file and do a pull request again?

Thanks.

**Review by ZahraB21 — APPROVED** [review]
Well done @rdhayaalan

**Pull request merged**
